[package]
name = "async-uring"
version = "0.1.0"
edition = "2024"

[dependencies]
async-event = "0.2.1"
diatomic-waker = "0.2.3"
flume = "0.11.1"
futures = { version = "0.3.31", default-features = false, features = ["std", "async-await"] }
io-uring = "0.7.4"
libc = "0.2.171"
pin-project-lite = "0.2.16"
slab = "0.4.9"
tagptr = "0.2.0"
thiserror = "2.0.12"
tokio = { version = "1.44.1", features = ["net"], optional = true }

[dev-dependencies]
tokio = { version = "1.44.1", features = ["rt", "rt-multi-thread", "macros", "net"], default-features = false }

[features]
default = ["tokio"]
tokio = ["dep:tokio"]

[[example]]
name = "echo"
required-features = ["tokio"]

[profile.release]
debug = true
lto = true
